const menuList = [
    {
        title:'Home',
        key:'/admin/home'
    },
    {
        title:'UI',
        key:'/admin/ui',
        children:[
            {
                title:'Buttons',
                key:'/admin/ui/buttons',
            },
            {
                title:'Modals',
                key:'/admin/ui/modals',
            },
            {
                title:'Loading',
                key:'/admin/ui/loadings',
            },
            {
                title:'Notification',
                key:'/admin/ui/notification',
            },
            {
                title:'GlobalMessage',
                key:'/admin/ui/messages',
            },
            {
                title:'Tabs',
                key:'/admin/ui/tabs',
            },
            {
                title:'Gallery',
                key:'/admin/ui/gallery',
            },
            {
                title:'Carousel',
                key:'/admin/ui/carousel',
            }
        ]
    },
    {
        title:'Form',
        key:'/form',
        children:[
            {
                title:'Login',
                key:'/admin/form/login',
            },
            {
                title:'Sign Up',
                key:'/admin/form/reg',
            }
        ]
    },
    {
        title:'Table',
        key:'/admin/table',
        children:[
            {
                title:'Basic Table',
                key:'/admin/table/basic',
            },
            {
                title:'Detail Table',
                key:'/admin/table/high',
            }
        ]
    },
    {
        title:'Rich Text',
        key:'/admin/rich'
    },
    {
        title:'City Management',
        key:'/admin/city'
    },
    {
        title:'Order',
        key:'/order',
        btnList:[
            {
                title:'Order Detail',
                key:'detail'
            },
            {
                title:'Order Manage',
                key:'finish'
            }
        ]
    },
    {
        title:'User Manage',
        key:'/admin/user'
    },
    {
        title:'Map',
        key:'/admin/bikeMap'
    },
    {
        title:'Charts',
        key:'/admin/charts',
        children:[
            {
                title:'Bar',
                key:'/admin/charts/bar'
            },
            {
                title:'Pie',
                key:'/admin/charts/pie'
            },
            {
                title:'Line',
                key:'/admin/charts/line'
            },
        ]
    },
    {
        title:'Permission Management',
        key:'admin//permission'
    },
];
export default menuList;